steps:
- name: 'gcr.io/cloud-builders/gradle'
  args: ['build -x test']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/reactive-backend', '.']
images: ['gcr.io/$PROJECT_ID/reactive-backend']